name: Deploy Earlier focus sessions fix

on:
    push:
        branches: [feature/earlier-sessions-fix]

    workflow_dispatch:

jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get latest code
              uses: actions/checkout@v2.3.2

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  server: hera.fhict.nl
                  username: ${{ secrets.HERA_TESTS_USERNAME }}
                  password: ${{ secrets.HERA_TESTS_PASSWORD }}
                  server-dir: ${{ secrets.HERA_TESTS_REMOTE }}
                  local-dir: src/
                  exclude: webshop/
                    - *.scss
