name: Deploy dev

on:
    push:
        branches: [master]

    workflow_dispatch:

jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get latest code
              uses: actions/checkout@v2.3.2

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  server: ${{ secrets.HERA_REGISTRY }}
                  username: ${{ secrets.HERA_USERNAME }}
                  password: ${{ secrets.HERA_PASSWORD }}
                  server-dir: ${{ secrets.HERA_REMOTE }}
                  local-dir: src/
                  exclude: webshop/
                      - *.scss
